# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GRAmrRuyOK_Wfz-Aile_Itl4iGGK52hZ
"""

import matplotlib.pyplot as plt
import numpy as np

x = np.random.rand(100)  # X o'qi uchun tasodifiy sonlar
y = np.random.rand(100)  # Y o'qi uchun tasodifiy sonlar


plt.scatter(x, y)  # scatter() funksiyasi tasodifiy nuqtalar uchun
plt.title('Tasodifiy Nuqtalar Grafi')  # Grafikka sarlavha qo'shamiz
plt.xlabel('X o\'qi')  # X o'qi nomi
plt.ylabel('Y o\'qi')  # Y o'qi nomi
plt.grid(True)  # Tarmoq chizish
plt.show()  # Grafikni ko'rsatish

import matplotlib.pyplot as plt
import numpy as np

x = np.linspace(-2 * np.pi, 2 * np.pi, 400)  # 400 ta nuqta bilan -2pi dan 2pi gacha

y = np.sin(x)

plt.plot(x, y, label='sin(x)')  # sin(x) ni chizamiz
plt.title('Sinus Funksiyasining Grafigi')  # Grafikka sarlavha qo'shamiz
plt.xlabel('X o\'qi')  # X o'qi nomi
plt.ylabel('Y o\'qi')  # Y o'qi nomi
plt.axhline(0, color='black',linewidth=0.5)  # Y o'qini chizish
plt.axvline(0, color='black',linewidth=0.5)  # X o'qini chizish
plt.grid(True)  # Tarmoqni ko'rsatish
plt.legend()  # Legenda qo'shish
plt.show()  # Grafika ko'rsatish

from PIL import Image


def convert_to_black_and_white(input_path, output_path):

    img = Image.open(input_path)

    bw_img = img.convert("L")

    bw_img.save(output_path)
    print(f"Oq-qora rasm saqlandi: {output_path}")

# Dastur ishga tushishi
input_file = "3. sirtlon.jpg"
output_file = "output_bw.jpg"

convert_to_black_and_white(input_file, output_file)

import pandas as pd


data = {
    "Mamlakat": ["hitoy", "Hindiston", "afrika", "koreya", "germanya"],
    "Kasallar soni": [30000000, 45000000, 22000000, 9000000, 12000000],
    "Vafot etganlar": [800000, 500000, 600000, 400000, 500000],
    "Sog'ayganlar": [65000000, 30000000, 20000000, 7000000, 70000000]
}


df = pd.DataFrame(data)


def analyze_covid_data(df):
    print("1. COVID-19 bo'yicha jadval ma'lumotlari:")
    print(df, "\n")

    print("2. Umumiy kasallar soni:")
    print(df["Kasallar soni"].sum(), "\n")

    print("3. Umumiy vafot etganlar soni:")
    print(df["Vafot etganlar"].sum(), "\n")

    print("4. Umumiy sog'ayganlar soni:")
    print(df["Sog'ayganlar"].sum(), "\n")

    print("5. O'lim foizi (%):")
    df["O'lim foizi (%)"] = (df["Vafot etganlar"] / df["Kasallar soni"]) * 100
    print(df[["Mamlakat", "O'lim foizi (%)"]], "\n")

    print("6. Eng ko'p vafot etganlar qaysi mamlakatda:")
    max_deaths = df[df["Vafot etganlar"] == df["Vafot etganlar"].max()]
    print(max_deaths[["Mamlakat", "Vafot etganlar"]], "\n")

    print("7. Eng yuqori o'lim foizi qaysi mamlakatda:")
    max_death_rate = df[df["O'lim foizi (%)"] == df["O'lim foizi (%)"].max()]
    print(max_death_rate[["Mamlakat", "O'lim foizi (%)"]], "\n")


analyze_covid_data(df)